//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public int IdUsuario { get; set; }
        public Nullable<int> Dni { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Usuario1 { get; set; }
        public string Clave { get; set; }
        public Nullable<int> IdRol { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    
        public virtual ROL ROL { get; set; }
    }
}
